language: java
install: true
jdk:
- oraclejdk11

before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"

jobs:
  include:
    - stage: test
      script:
        - "./gradlew build --scan --stacktrace"
    - stage: deploy_prod
      script:
        - "./gradlew build --scan --stacktrace"
        - openssl aes-256-cbc -K $encrypted_0febda2b5ff0_key -iv $encrypted_0febda2b5ff0_iv 
          -in deploy_key.enc -out ./deploy_key -d
        - eval "$(ssh-agent -s)"
        - chmod 600 ./deploy_key
        - echo -e "Host $PROD_IP\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
        - ssh-add ./deploy_key
        - ssh $PROD_SERVER_USER@$PROD_IP $PROD_SCRIPT_PATH/clean.sh
        - scp ./build/libs/ctf-admin-0.1.0.jar $PROD_SERVER_USER@$PROD_IP:$PROD_APP_PATH/ctf-admin.jar
        - ssh $PROD_SERVER_USER@$PROD_IP $PROD_SCRIPT_PATH/start.sh
    - stage: deploy_test
      script:
        - openssl aes-256-cbc -K $encrypted_0febda2b5ff0_key -iv $encrypted_0febda2b5ff0_iv
        -in deploy_key.enc -out ./deploy_key -d
        - eval "$(ssh-agent -s)"
        - chmod 600 ./deploy_key
        - echo -e "Host $TEST_IP\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
        - ssh-add ./deploy_key
        - ssh $TEST_SERVER_USER@$TEST_IP $TEST_SCRIPT_PATH/clean.sh
        - scp ./build/libs/ctf-admin-0.1.0.jar $TEST_SERVER_USER@$TEST_IP:$TEST_APP_PATH/ctf-admin.jar
        - ssh $TEST_SERVER_USER@$TEST_IP $TEST_SCRIPT_PATH/start.sh

stages:
  - name: test
    if: type = pull_request
  - name: deploy_prod
    if: type = push AND branch = master
  - name: deploy_test
    if: type = push AND branch = test-server
